espritsocialpro_homepage:
    path:     /index
    defaults: { _controller: EspritsocialproBundle:Default:index }

espritsocialpro_profil:
    path:     /profil
    defaults: { _controller: EspritsocialproBundle:Profil:index }

espritsocialpro_filactualite:
    path:     /Filactualite
    defaults: { _controller: EspritsocialproBundle:Filactualite:index }

espritsocialpro_employes:
    path:     /Employes
    defaults: { _controller: EspritsocialproBundle:Employes:index }

espritsocialpro_ajoutemployes:
    path:     /AjoutEmployes
    defaults: { _controller: EspritsocialproBundle:Employes:ajoutemployes }

espritsocialpro_demandeinscrptionemployes:
    path:     /DemandeEmployes
    defaults: { _controller: EspritsocialproBundle:Employes:demandeinscrption }
supp_employe:
    path:     /suppEmploye/{id}
    defaults: { _controller: EspritsocialproBundle:Employes:supprimer }
modif_employe:
    path:     /modifEmploye/{id}
    defaults: { _controller: EspritsocialproBundle:Employes:modifier }

espritsocialpro_departements:
    path:     /Departements
    defaults: { _controller: EspritsocialproBundle:Departement:index }

espritsocialpro_departementsaffectation:
    path:     /Affectations
    defaults: { _controller: EspritsocialproBundle:Departement:affectation }

espritsocialpro_reunions:
    path:     /Reunions
    defaults: { _controller: EspritsocialproBundle:Reunion:index }

espritsocialpro_gestionreunions:
    path:     /GestionReunions
    defaults: { _controller: EspritsocialproBundle:Reunion:gestionreunion }

espritsocialpro_gestionsallesreunions:
    path:     /GestionSallesReunions
    defaults: { _controller: EspritsocialproBundle:Reunion:gestionsallereunion }

espritsocialpro_ajoutsallesreunions:
    path:     /AjoutSallesReunions
    defaults: { _controller: EspritsocialproBundle:Reunion:ajoutsallereunion }

espritsocialpro_supprimersallesreunions:
    path:     /suppSalle/{id}
    defaults: { _controller: EspritsocialproBundle:Reunion:supprimer }

espritsocialpro_modifierersallesreunions:
    path:     /modifierSalle/{id}
    defaults: { _controller: EspritsocialproBundle:Reunion:modifiersalle }

espritsocialpro_projets:
    path:     /Projets
    defaults: { _controller: EspritsocialproBundle:Projets:index }

espritsocialpro_ajout_projets:
    path:     /addProjets
    defaults: { _controller: EspritsocialproBundle:Projets:ajout }

espritsocialpro_supp_projets:
    path:     /suppProjets/{idprojet}
    defaults: { _controller: EspritsocialproBundle:Projets:supprime }

espritsocialpro_update_projets:
    path:     /updateProjets/{idprojet}
    defaults: { _controller: EspritsocialproBundle:Projets:update }

espritsocialpro_taches:
    path:     /Taches
    defaults: { _controller: EspritsocialproBundle:Projets:taches }


espritsocialpro_equipes:
    path:     /Equipes
    defaults: { _controller: EspritsocialproBundle:Projets:equipes }

espritsocialpro_gestionprojets:
    path:     /GestionProjets
    defaults: { _controller: EspritsocialproBundle:Projets:affiche }

espritsocialpro_offres:
    path:     /Offres
    defaults: { _controller: EspritsocialproBundle:Offres:index }

espritsocialpro_ajoutoffre:
    path:     /ajoutoffre
    defaults: { _controller: EspritsocialproBundle:Offres:ajout }
espritsocialpro_suppoffre:
    path:     /suppoffre/{id}
    defaults: { _controller: EspritsocialproBundle:Offres:supp }
espritsocialpro_modifoffre:
    path:     /modifoffre/{id}
    defaults: { _controller: EspritsocialproBundle:Offres:update }

espritsocialpro_forum:
    path:     /Forum
    defaults: { _controller: EspritsocialproBundle:Forum:index }

espritsocialpro_support:
    path:     /Support
    defaults: { _controller: EspritsocialproBundle:Forum:support }

espritsocialpro_statistiques:
    path:     /Statistiques
    defaults: { _controller: EspritsocialproBundle:Statistiques:index }

espritsocialpro_historique:
    path:     /Historique
    defaults: { _controller: EspritsocialproBundle:Historique:index }

espritsocialpro_calendrier:
    path:     /Calendrier
    defaults: { _controller: EspritsocialproBundle:Calendrier:index }
espritsocialpro_departement:
    path:     /ajoutDepartement
    defaults: { _controller: EspritsocialproBundle:Departement:ajout }

supp_departement:
    path:     /suppDepartement/{id}
    defaults: { _controller: EspritsocialproBundle:Departement:supprimer }

modifier_departement:
    path:     /modifierDepartement/{id}
    defaults: { _controller: EspritsocialproBundle:Departement:modifier }

modifiercontact:
    path:     /modifiercontact
    defaults: { _controller: EspritsocialproBundle:Profil:modifiercontact }
modifierinfos:
    path:     /modifierinfos
    defaults: { _controller: EspritsocialproBundle:Profil:modifierinfos }
modifierdescription:
    path:     /modifierdescription
    defaults: { _controller: EspritsocialproBundle:Profil:modifierdesc }
rechercherconnecter:
    path:     /rechercherconnecter
    defaults: { _controller: EspritsocialproBundle:Profil:rechercherconnecter }
modifieretat:
    path:     /modifieretat
    defaults: { _controller: EspritsocialproBundle:Profil:modifierindisponnible }
deconnecting:
    path:     /deconnecter
    defaults: { _controller: EspritsocialproBundle:Profil:deconnecteretat }
connecting:
    path:     /connecter
    defaults: { _controller: EspritsocialproBundle:Profil:connecteretat }
profilami:
    path:     /profilAmi/{id}
    defaults: { _controller: EspritsocialproBundle:Profil:ProfilAmi }
ajouterimagecertif:
    path:     /ajouterimagecertif/{id}
    defaults: { _controller: EspritsocialproBundle:Certification:ajouterimage }
ajouterCertification:
    path:     /ajoutercertification
    defaults: { _controller: EspritsocialproBundle:Certification:AjouterCertification }
ajoutercompetence:
    path:     /ajoutercompetence
    defaults: { _controller: EspritsocialproBundle:Certification:Ajoutercompetence }
affichercompetence:
    path:     /affichecompetence
    defaults: { _controller: EspritsocialproBundle:Certification:AfficherCompetence }