espritsocialpro_homepage:
    path:     /index
    defaults: { _controller: EspritsocialproBundle:Default:index }

espritsocialpro_profil:
    path:     /profil
    defaults: { _controller: EspritsocialproBundle:Profil:index }

espritsocialpro_profil_photos:
    path:     /photos
    defaults: { _controller: EspritsocialproBundle:Profil:photos }

espritsocialpro_filactualite:
    path:     /Filactualite
    defaults: { _controller: EspritsocialproBundle:Filactualite:index }

espritsocialpro_employes:
    path:     /Employes
    defaults: { _controller: EspritsocialproBundle:Employes:index }

espritsocialpro_ajoutemployes:
    path:     /AjoutEmployes
    defaults: { _controller: EspritsocialproBundle:Employes:ajoutemployes }

espritsocialpro_demandeinscrptionemployes:
    path:     /DemandeEmployes
    defaults: { _controller: EspritsocialproBundle:Employes:demandeinscrption }

espritsocialpro_departements:
    path:     /Departements
    defaults: { _controller: EspritsocialproBundle:Departement:index }

espritsocialpro_departementsaffectation:
    path:     /Affectations
    defaults: { _controller: EspritsocialproBundle:Departement:affectation }

espritsocialpro_reunions:
    path:     /Reunions
    defaults: { _controller: EspritsocialproBundle:Reunion:index }

espritsocialpro_gestionreunions:
    path:     /GestionReunions
    defaults: { _controller: EspritsocialproBundle:Reunion:gestionreunion }

espritsocialpro_projets:
    path:     /Projets
    defaults: { _controller: EspritsocialproBundle:Projets:index }

espritsocialpro_taches:
    path:     /Taches
    defaults: { _controller: EspritsocialproBundle:Projets:taches }

espritsocialpro_equipes:
    path:     /Equipes
    defaults: { _controller: EspritsocialproBundle:Projets:equipes }

espritsocialpro_gestionprojets:
    path:     /GestionProjets
    defaults: { _controller: EspritsocialproBundle:Projets:gestionprojets }

espritsocialpro_offres:
    path:     /Offres
    defaults: { _controller: EspritsocialproBundle:Offres:index }

espritsocialpro_ajoutoffre:
    path:     /ajoutoffre
    defaults: { _controller: EspritsocialproBundle:Offres:ajout }

espritsocialpro_forum:
    path:     /Forum
    defaults: { _controller: EspritsocialproBundle:Forum:index }

espritsocialpro_support:
    path:     /Support
    defaults: { _controller: EspritsocialproBundle:Forum:support }

espritsocialpro_statistiques:
    path:     /Statistiques
    defaults: { _controller: EspritsocialproBundle:Statistiques:index }

espritsocialpro_historique:
    path:     /Historique
    defaults: { _controller: EspritsocialproBundle:Historique:index }

espritsocialpro_calendrier:
    path:     /Calendrier
    defaults: { _controller: EspritsocialproBundle:Calendrier:index }
