<?php

namespace Esprit\socialproBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * UserRepository
 *
 * This class was generated by the PhpStorm "Php Annotations" Plugin. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository
{
    public function findConnected(){
        $query=$this->getEntityManager()->createQuery("SELECT u FROM EspritsocialproBundle:User u WHERE u.connected=1 OR u.connected=2 ");
        return $query->getResult();
    }
}
